"""reduced size

Revision ID: 82c3e1ab8387
Revises: e27b82847f1a
Create Date: 2021-08-16 18:10:41.733607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c3e1ab8387'
down_revision = 'e27b82847f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
