"""second

Revision ID: 8f518ec992a9
Revises: e89aef8eb089
Create Date: 2021-08-16 18:18:32.183012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f518ec992a9'
down_revision = 'e89aef8eb089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
