"""change

Revision ID: b5b37e9d6f40
Revises: d42e3d1b9030
Create Date: 2021-08-16 18:05:50.039539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b37e9d6f40'
down_revision = 'd42e3d1b9030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
