"""new

Revision ID: d42e3d1b9030
Revises: c99b30591f4a
Create Date: 2021-08-16 17:56:37.833410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42e3d1b9030'
down_revision = 'c99b30591f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
