"""first

Revision ID: e89aef8eb089
Revises: 82c3e1ab8387
Create Date: 2021-08-16 18:15:23.649576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89aef8eb089'
down_revision = '82c3e1ab8387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=16), nullable=True),
    sa.Column('hashed_password', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_email'), 'copy', ['email'], unique=True)
    op.create_index(op.f('ix_copy_id'), 'copy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copy_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_email'), table_name='copy')
    op.drop_table('copy')
    # ### end Alembic commands ###
